In [1]:
import pandas as pd
import numpy as np
import random
import pandas as pd
import collections
import scipy.io
import csv
import math

In [2]:
table = pd.read_csv('final_data.csv')
table.fillna(0, inplace=True)
table.head()

Unnamed: 0  CouId          County  CrmRatePer100k  MURDER  RAPE  ROBBERY  \
0           0   1001  Autauga County      251.601926     3.0  15.0     34.0   
1           1   1003  Baldwin County      228.086325     8.0  30.0     76.0   
2           2   1005  Barbour County      177.278771     0.0   4.0      8.0   
3           3   1007     Bibb County      217.661691     1.0   4.0      8.0   
4           4   1009   Blount County      210.810064     1.0  11.0      9.0   

   AGASSLT  BURGLRY  LARCENY  ...  Walk  OtherTransp  WorkAtHome  MeanCommute  \
0     87.0    447.0   1233.0  ...   0.6          1.3         2.5         25.8   
1    332.0    967.0   3829.0  ...   0.8          1.1         5.6         27.0   
2     36.0     90.0    362.0  ...   2.2          1.7         1.3         23.4   
3     36.0    122.0    251.0  ...   0.3          1.7         1.5         30.0   
4    101.0    397.0    865.0  ...   0.4          0.4         2.1         35.0   

  Employed  PrivateWork  PublicWork  SelfEmployed  FamilyWork  Unemployment  
0    24112         74.1        20.2           5.6         0.1           5.2  
1    89527         80.7        12.9           6.3         0.1           5.5  
2     8878         74.1        19.1           6.5         0.3          12.4  
3     8171         76.0        17.4           6.3         0.3           8.2  
4    21380         83.9        11.9           4.0         0.1           4.9  

[5 rows x 49 columns]

In [3]:
for col in table.columns: 
    print(col) 

Unnamed: 0
CouId
County
CrmRatePer100k
MURDER
RAPE
ROBBERY
AGASSLT
BURGLRY
LARCENY
Pop
SumVCrm
SumVCrm/Pop
%SumVCrm/Pop
State
TotalPop
Men
Women
Hispanic
White
Black
Native
Asian
Pacific
VotingAgeCitizen
Income
IncomeErr
IncomePerCap
IncomePerCapErr
Poverty
ChildPoverty
Professional
Service
Office
Construction
Production
Drive
Carpool
Transit
Walk
OtherTransp
WorkAtHome
MeanCommute
Employed
PrivateWork
PublicWork
SelfEmployed
FamilyWork
Unemployment


In [4]:
income = np.array(table['Income'].rank(pct=True))
for i in range(len(income)):
    income[i] *= 10
    income[i] = round(income[i], 2)
print(income)
table['Income'].mean()

[7.43 6.66 0.59 ... 7.27 6.21 8.34]


49705.00997672098

In [5]:
poverty = np.array(table['Poverty'].rank(pct=True))
for i in range(len(poverty)):
    poverty[i] = 1 - poverty[i]
for i in range(len(poverty)):
    poverty[i] *= 10
    poverty[i] = round(poverty[i], 2)
print(poverty)
table['Poverty'].mean()

[5.86 7.16 0.51 ... 5.09 6.56 5.4 ]


15.85623545061525

In [6]:
population = np.array(table['TotalPop'].rank(pct=True))
for i in range(len(population)):
    population[i] *= 10
    population[i] = round(population[i], 2)
print(population)
table['TotalPop'].mean()

[7.08 8.99 5.05 ... 4.32 1.78 1.52]


103558.67708679747

In [7]:
childPoverty = np.array(table['ChildPoverty'].rank(pct=True))
for i in range(len(childPoverty)):
    childPoverty[i] = 1 - childPoverty[i]
for i in range(len(childPoverty)):
    childPoverty[i] *= 10
    childPoverty[i] = round(childPoverty[i], 2)
print(childPoverty)
table['ChildPoverty'].mean()

[5.35 6.96 0.28 ... 5.42 6.43 3.72]


21.922414366478254

In [8]:
unemployment = np.array(table['Unemployment'].rank(pct=True))
for i in range(len(unemployment)):
    unemployment[i] = 1 - unemployment[i]
for i in range(len(unemployment)):
    unemployment[i] *= 10
    unemployment[i] = round(unemployment[i], 2)
print(unemployment)
table['Unemployment'].mean()

[6.29 5.81 0.32 ... 4.34 4.84 9.45]


6.284901895576985

In [9]:
commute = np.array(table['MeanCommute'].rank(pct=True))
for i in range(len(commute)):
    commute[i] = 1 - commute[i]
for i in range(len(commute)):
    commute[i] *= 10
    commute[i] = round(commute[i], 2)
print(commute)
table['MeanCommute'].mean()

[3.07 2.41 4.78 ... 7.3  9.62 3.14]


23.409910209511178

In [10]:
crimeRate = np.array(table['CrmRatePer100k'].rank(pct=True))
for i in range(len(crimeRate)):
    crimeRate[i] = 1 - crimeRate[i]
for i in range(len(crimeRate)):
    crimeRate[i] *= 10
    crimeRate[i] = round(crimeRate[i], 2)
print(crimeRate)
table['CrmRatePer100k'].mean()

[3.53 4.05 5.12 ... 9.14 8.42 8.14]


229.59070396703558

In [11]:
table['violent'] = table.apply(lambda row: (row.MURDER + row.RAPE + row.ROBBERY)/row.Pop, axis=1)
violentCrime = np.array(table['violent'].rank(pct=True))
for i in range(len(violentCrime)):
    violentCrime[i] = 1 - violentCrime[i]
for i in range(len(violentCrime)):
    violentCrime[i] *= 10
    violentCrime[i] = round(violentCrime[i], 2)
print(violentCrime)
table['violent'].mean()

[1.77 3.65 4.91 ... 7.87 9.33 7.9 ]


0.0005792761181876592

In [12]:
table['economyScore'] = income*0.5 + poverty*0.3 + childPoverty*0.2
table['economyScore'] = table['economyScore'].round(1)
print(table['economyScore'])

0       6.5
1       6.9
2       0.5
3       3.7
4       4.4
5       0.3
6       1.0
7       3.1
8       1.9
9       3.4
10      2.9
11      0.9
12      0.9
13      2.2
14      1.8
15      4.7
16      3.9
17      0.4
18      3.3
19      2.6
20      2.8
21      3.6
22      3.1
23      0.2
24      1.7
25      6.5
26      1.0
27      2.8
28      2.1
29      1.4
       ... 
2977    5.2
2978    9.6
2979    9.8
2980    7.2
2981    6.2
2982    7.2
2983    6.9
2984    4.1
2985    6.7
2986    9.1
2987    7.4
2988    9.1
2989    9.5
2990    6.6
2991    5.6
2992    5.6
2993    7.5
2994    8.5
2995    8.8
2996    8.3
2997    3.7
2998    9.0
2999    6.0
3000    8.7
3001    9.7
3002    8.2
3003    9.7
3004    6.2
3005    6.4
3006    6.5
Name: economyScore, Length: 3007, dtype: float64


In [13]:
table['safetyScore'] = crimeRate*0.7 + violentCrime*0.3
table['safetyScore'] = table['safetyScore'].round(1)
print(table['safetyScore'])

0       3.0
1       3.9
2       5.1
3       4.1
4       4.7
5       0.8
6       0.9
7       0.6
8       1.0
9       3.0
10      2.4
11      7.7
12      1.1
13      3.0
14      5.5
15      3.2
16      1.2
17      0.7
18      5.0
19      3.6
20      2.0
21      4.3
22      1.7
23      0.1
24      2.8
25      2.7
26      1.1
27      0.8
28      3.6
29      1.5
       ... 
2977    6.2
2978    7.4
2979    8.0
2980    6.9
2981    6.5
2982    5.2
2983    8.3
2984    6.1
2985    6.4
2986    7.0
2987    3.5
2988    4.4
2989    7.0
2990    4.8
2991    4.8
2992    7.0
2993    6.0
2994    3.7
2995    8.7
2996    5.4
2997    7.5
2998    3.5
2999    8.6
3000    7.3
3001    7.2
3002    2.0
3003    5.7
3004    8.8
3005    8.7
3006    8.1
Name: safetyScore, Length: 3007, dtype: float64


In [14]:
table['communityScore'] = unemployment*0.3 + commute*0.3 + population*0.4
table['communityScore'] = table['communityScore'].round(1)
print(table['communityScore'])

0       5.6
1       6.1
2       3.6
3       2.8
4       5.0
5       1.4
6       4.0
7       4.7
8       5.0
9       4.6
10      3.9
11      1.6
12      3.3
13      2.8
14      2.2
15      6.1
16      5.4
17      1.6
18      1.5
19      3.7
20      3.0
21      5.5
22      5.0
23      4.3
24      6.5
25      4.6
26      4.1
27      5.4
28      2.6
29      3.4
       ... 
2977    5.1
2978    7.2
2979    7.7
2980    6.7
2981    4.7
2982    8.5
2983    7.4
2984    7.5
2985    5.6
2986    6.9
2987    6.7
2988    4.2
2989    3.7
2990    6.5
2991    4.9
2992    5.0
2993    4.2
2994    7.8
2995    4.0
2996    7.7
2997    6.0
2998    7.3
2999    6.2
3000    7.6
3001    5.2
3002    6.6
3003    7.7
3004    5.2
3005    5.0
3006    4.4
Name: communityScore, Length: 3007, dtype: float64


In [15]:
table['overallScore'] = table.apply(lambda row: row.economyScore*0.4 + row.communityScore*0.3 + row.safetyScore*0.3 + 1, axis=1)
table['overallScore'] = table['overallScore'].round(1)
print(table['overallScore'])

best = max(table['overallScore'])
worst = min(table['overallScore'])
[i for i, j in enumerate(table['overallScore']) if j == best]

0       6.2
1       6.8
2       3.8
3       4.6
4       5.7
5       1.8
6       2.9
7       3.8
8       3.6
9       4.6
10      4.0
11      4.2
12      2.7
13      3.6
14      4.0
15      5.7
16      4.5
17      1.8
18      4.3
19      4.2
20      3.6
21      5.4
22      4.2
23      2.4
24      4.5
25      5.8
26      3.0
27      4.0
28      3.7
29      3.0
       ... 
2977    6.5
2978    9.2
2979    9.6
2980    8.0
2981    6.8
2982    8.0
2983    8.5
2984    6.7
2985    7.3
2986    8.8
2987    7.0
2988    7.2
2989    8.0
2990    7.0
2991    6.2
2992    6.8
2993    7.1
2994    7.8
2995    8.3
2996    8.2
2997    6.5
2998    7.8
2999    7.8
3000    9.0
3001    8.6
3002    6.9
3003    8.9
3004    7.7
3005    7.7
3006    7.4
Name: overallScore, Length: 3007, dtype: float64


[695]

In [16]:
names = np.array(table)
names[695]

array([695, 18057, 'Hamilton County', 33.70487339, 0.0, 13.0, 31.0, 56.0,
       422.0, 2420.0, 296693.0, 2942.0, 0.009915973750644605,
       0.9915973750644606, 'Indiana', 309687, 151395, 158292, 3.8, 84.5,
       3.6, 0.1, 5.7, 0.0, 212065, 90582, 1988, 44443, 1040, 5.0, 5.8,
       53.3, 11.1, 24.7, 5.0, 6.0, 83.5, 6.9, 0.2, 0.8, 0.7, 7.9, 25.5,
       163999, 86.0, 9.5, 4.4, 0.1, 3.3, 0.00014830144290562972, 9.8, 8.7,
       7.3, 9.7], dtype=object)

In [18]:
table

Unnamed: 0  CouId              County  CrmRatePer100k  MURDER  RAPE  \
0              0   1001      Autauga County      251.601926     3.0  15.0   
1              1   1003      Baldwin County      228.086325     8.0  30.0   
2              2   1005      Barbour County      177.278771     0.0   4.0   
3              3   1007         Bibb County      217.661691     1.0   4.0   
4              4   1009       Blount County      210.810064     1.0  11.0   
5              5   1011      Bullock County      526.365260     0.0   2.0   
6              6   1013       Butler County      537.873180     6.0   5.0   
7              7   1015      Calhoun County      580.797697     6.0  37.0   
8              8   1017     Chambers County      562.027984     1.0   7.0   
9              9   1019     Cherokee County      415.982903     1.0   4.0   
10            10   1021      Chilton County      354.940729     0.0  13.0   
11            11   1023      Choctaw County       96.827052     1.0   0.0   
12            12   1025       Clarke County      480.025390     0.0  16.0   
13            13   1027         Clay County      430.075634     0.0   0.0   
14            14   1029     Cleburne County      193.410698     0.0   1.0   
15            15   1031       Coffee County      341.591739     2.0   5.0   
16            16   1033      Colbert County      482.391783     2.0  15.0   
17            17   1035      Conecuh County      644.059905     1.0   4.0   
18            18   1037        Coosa County      192.695908     0.0   2.0   
19            19   1039    Covington County      258.670749     1.0  13.0   
20            20   1041     Crenshaw County      479.050479     1.0   3.0   
21            21   1043      Cullman County      237.591417     2.0  16.0   
22            22   1045         Dale County      410.953412     1.0   8.0   
23            23   1047       Dallas County      828.650348     9.0  24.0   
24            24   1049       DeKalb County      381.620267     0.0  20.0   
25            25   1051       Elmore County      284.294579     4.0  23.0   
26            26   1053     Escambia County      618.697838     3.0   7.0   
27            27   1055       Etowah County      513.802427     2.0  45.0   
28            28   1057      Fayette County      230.646401     1.0   9.0   
29            29   1059     Franklin County      497.906888     0.0  10.0   
...          ...    ...                 ...             ...     ...   ...   
2977        2977  55129     Washburn County      146.627566     0.0   4.0   
2978        2978  55131   Washington County       89.649613     2.0  10.0   
2979        2979  55133     Waukesha County       61.953621     4.0  38.0   
2980        2980  55135      Waupaca County      109.017883     0.0   9.0   
2981        2981  55137     Waushara County      110.978667     0.0   8.0   
2982        2982  55139    Winnebago County      189.334733     0.0  28.0   
2983        2983  55141         Wood County       40.563015     1.0   7.0   
2984        2984  56001       Albany County      117.577895     1.0  15.0   
2985        2985  56003     Big Horn County      125.062531     0.0   3.0   
2986        2986  56005     Campbell County      128.694786     0.0   1.0   
2987        2987  56007       Carbon County      247.650495     0.0  10.0   
2988        2988  56009     Converse County      237.546287     0.0   5.0   
2989        2989  56011        Crook County       83.518931     0.0   3.0   
2990        2990  56013      Fremont County      163.422606     2.0  21.0   
2991        2991  56015       Goshen County      271.818983     0.0   0.0   
2992        2992  56017  Hot Springs County      144.419228     0.0   0.0   
2993        2993  56019      Johnson County      162.262401     1.0   1.0   
2994        2994  56021      Laramie County      236.929725     2.0  33.0   
2995        2995  56023      Lincoln County       59.899804     0.0   0.0   
2996        2996  56025      Natrona County      187.716893     3.0   7.0   
29

In [17]:
table.to_csv('final_results.csv')